# Generated by Django 4.1.7 on 2023-04-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(default='unknown', max_length=225),
        ),
        migrations.AddField(
            model_name='client',
            name='org_name',
            field=models.CharField(default='unknown', max_length=225),
        ),
    ]
