# Generated by Django 4.1.7 on 2023-04-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_industry_client_org_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='industry',
        ),
    ]
