# Generated by Django 4.1.7 on 2023-04-24 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0008_client_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='customer_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('store', 'Store')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_rep', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='total_order_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
