# Generated by Django 4.1.7 on 2023-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='converted_leads',
            field=models.IntegerField(default=0),
        ),
    ]
